"""Added gender field

Revision ID: 8ce21e4e028a
Revises: 
Create Date: 2025-03-22 21:25:58.045781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce21e4e028a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roommate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=15), nullable=False, server_default='unspecified'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roommate', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
